"""Farm assign to one customer only 1

Revision ID: 0250839094db
Revises: 2480627e9bc2
Create Date: 2023-12-06 16:49:47.220274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0250839094db'
down_revision: Union[str, None] = '2480627e9bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farm_assignment')
    op.add_column('farms', sa.Column('assigned_customer', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'farms', 'users', ['assigned_customer'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farms', type_='foreignkey')
    op.drop_column('farms', 'assigned_customer')
    op.create_table('farm_assignment',
    sa.Column('farm_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.farm_id'], name='farm_assignment_farm_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='farm_assignment_user_id_fkey', ondelete='CASCADE'),
    sa.UniqueConstraint('farm_id', name='farm_assignment_farm_id_key')
    )
    # ### end Alembic commands ###
