"""Farm assign to one customer only

Revision ID: 2480627e9bc2
Revises: 79159ae62da4
Create Date: 2023-12-06 16:14:15.570894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2480627e9bc2'
down_revision: Union[str, None] = '79159ae62da4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('farm_assignment_farm_id_user_id_key', 'farm_assignment', type_='unique')
    op.create_unique_constraint(None, 'farm_assignment', ['farm_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farm_assignment', type_='unique')
    op.create_unique_constraint('farm_assignment_farm_id_user_id_key', 'farm_assignment', ['farm_id', 'user_id'])
    # ### end Alembic commands ###
