"""Add farm location

Revision ID: 29b8af0fbecb
Revises: 36ab930854c8
Create Date: 2024-01-20 14:27:57.642945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29b8af0fbecb'
down_revision: Union[str, None] = '36ab930854c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('location', sa.ARRAY(sa.Float()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'location')
    # ### end Alembic commands ###
