"""minor fixes again

Revision ID: 47b3702548d1
Revises: db3a22570012
Create Date: 2023-12-09 13:53:32.133060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b3702548d1'
down_revision: Union[str, None] = 'db3a22570012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('label', sa.String(length=100), nullable=True))
    op.add_column('farms', sa.Column('descriptions', sa.String(length=250), nullable=True))
    op.create_unique_constraint('uq_farm_key_pair', 'thresholds', ['farm_id', 'key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_farm_key_pair', 'thresholds', type_='unique')
    op.drop_column('farms', 'descriptions')
    op.drop_column('devices', 'label')
    # ### end Alembic commands ###
