"""Minor change for report again

Revision ID: 79159ae62da4
Revises: 801f6fa5a3d9
Create Date: 2023-12-05 00:15:34.346341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79159ae62da4'
down_revision: Union[str, None] = '801f6fa5a3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'farm_assignment', ['farm_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farm_assignment', type_='unique')
    # ### end Alembic commands ###
