"""Minor change for report

Revision ID: 801f6fa5a3d9
Revises: f0400d632fb8
Create Date: 2023-12-05 00:11:07.482862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801f6fa5a3d9'
down_revision: Union[str, None] = 'f0400d632fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_username_created_by_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['user_id', 'created_by'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_username_created_by_key', 'users', ['username', 'created_by'])
    # ### end Alembic commands ###
