"""change th att name

Revision ID: 81ff715f43f4
Revises: 4eaf5a9a027b
Create Date: 2023-12-09 15:21:14.803332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81ff715f43f4'
down_revision: Union[str, None] = '4eaf5a9a027b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thresholds', sa.Column('modified_by', sa.UUID(), nullable=False))
    op.add_column('thresholds', sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('thresholds_created_by_fkey', 'thresholds', type_='foreignkey')
    op.create_foreign_key(None, 'thresholds', 'users', ['modified_by'], ['user_id'], ondelete='CASCADE')
    op.drop_column('thresholds', 'created_by')
    op.drop_column('thresholds', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thresholds', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('thresholds', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'thresholds', type_='foreignkey')
    op.create_foreign_key('thresholds_created_by_fkey', 'thresholds', 'users', ['created_by'], ['user_id'], ondelete='CASCADE')
    op.drop_column('thresholds', 'modified_at')
    op.drop_column('thresholds', 'modified_by')
    # ### end Alembic commands ###
