"""Fix Name

Revision ID: 836227680059
Revises: ac4f9fca5b70
Create Date: 2024-03-02 18:02:59.751947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836227680059'
down_revision: Union[str, None] = 'ac4f9fca5b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera_sources', sa.Column('camera_source_name', sa.String(length=100), nullable=False))
    op.drop_column('camera_sources', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera_sources', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('camera_sources', 'camera_source_name')
    # ### end Alembic commands ###
