"""Fix Constraints

Revision ID: 891d03121d42
Revises: 4bcb46c7452c
Create Date: 2023-12-02 16:35:36.274002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891d03121d42'
down_revision: Union[str, None] = '4bcb46c7452c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_profiles_name_key', 'device_profiles', type_='unique')
    op.drop_constraint('devices_name_key', 'devices', type_='unique')
    op.drop_constraint('farms_name_key', 'farms', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('farms_name_key', 'farms', ['name'])
    op.create_unique_constraint('devices_name_key', 'devices', ['name'])
    op.create_unique_constraint('device_profiles_name_key', 'device_profiles', ['name'])
    # ### end Alembic commands ###
