"""Add not null on created by

Revision ID: 93b1446549de
Revises: 94ae4f58c343
Create Date: 2023-12-04 12:53:50.721560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b1446549de'
down_revision: Union[str, None] = '94ae4f58c343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
