"""Add user created by

Revision ID: 94ae4f58c343
Revises: f8a66c5dbd59
Create Date: 2023-12-04 12:41:21.046593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ae4f58c343'
down_revision: Union[str, None] = 'f8a66c5dbd59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'users', ['username', 'created_by'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'created_by')
    # ### end Alembic commands ###
