"""minor fix

Revision ID: db3a22570012
Revises: fc0296a305b7
Create Date: 2023-12-09 13:34:35.607202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3a22570012'
down_revision: Union[str, None] = 'fc0296a305b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('farms_assigned_customer_fkey', 'farms', type_='foreignkey')
    op.create_foreign_key(None, 'farms', 'users', ['assigned_customer'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farms', type_='foreignkey')
    op.create_foreign_key('farms_assigned_customer_fkey', 'farms', 'users', ['assigned_customer'], ['user_id'])
    # ### end Alembic commands ###
