"""Fix farm assign cascade, add thresholds table

Revision ID: fc0296a305b7
Revises: b9a5f13175d8
Create Date: 2023-12-09 13:30:27.526580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0296a305b7'
down_revision: Union[str, None] = 'b9a5f13175d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thresholds',
    sa.Column('threshold_id', sa.UUID(), nullable=False),
    sa.Column('farm_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('threshold_max', sa.Float(), nullable=True),
    sa.Column('threshold_min', sa.Float(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.farm_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['key'], ['ts_keys.ts_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('threshold_id')
    )
    op.drop_constraint('farms_assigned_customer_fkey', 'farms', type_='foreignkey')
    op.create_foreign_key(None, 'farms', 'users', ['assigned_customer'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farms', type_='foreignkey')
    op.create_foreign_key('farms_assigned_customer_fkey', 'farms', 'users', ['assigned_customer'], ['user_id'], ondelete='CASCADE')
    op.drop_table('thresholds')
    # ### end Alembic commands ###
